apiVersion: cluster.redpanda.com/v1alpha2
kind: Console
metadata:
  name: ref
  namespace: redpanda-system
spec:
  cluster:
    clusterRef:
      name: redpanda
  config:
    auditLog:
      enabled: true