apiVersion: cluster.redpanda.com/v1alpha2
kind: RedpandaRole
metadata:
  name: admin
  namespace: redpanda-system
spec:
  cluster:
    clusterRef:
      name: redpanda
  principals:
    - User:alice
  authorization:
    acls:
      - type: allow
        resource:
          type: topic
          name: public-
          patternType: prefixed
        operations: [Read, Describe]