apiVersion: cluster.redpanda.com/v1alpha2
kind: Redpanda
metadata:
  name: redpanda-console-enabled
  namespace: redpanda-system
spec:
  clusterSpec:
    image:
      repository: redpandadata/redpanda
      tag: v25.3.1
    auth:
      sasl:
        enabled: true
        users:
          - name: superuser
            password: superpassword
            mechanism: SCRAM-SHA-512
    external:
      enabled: false
    statefulset:
      replicas: 1
    config:
      cluster:
        enable_shadow_linking: true
    console:
      config:
        authentication:
          oidc:
            enabled: false
      console:
        login:
          plain:
            enabled: true
          jwtSecret: secret123
          useSecureCookies: true