apiVersion: cluster.redpanda.com/v1alpha2
kind: Redpanda
metadata:
  name: redpanda-nodepool
  namespace: redpanda-system
spec:
  clusterSpec:
    image:
      repository: redpandadata/redpanda
      tag: v25.3.1
    external:
      enabled: false
    statefulset:
      replicas: 0
    console:
      enabled: false
    config:
      cluster:
        enable_shadow_linking: true