apiVersion: cluster.redpanda.com/v1alpha2
kind: Redpanda
metadata:
  name: redpanda-shadow
  namespace: redpanda-system
spec:
  clusterSpec:
    image:
      repository: redpandadata/redpanda
      tag: v25.3.1
    auth:
      sasl:
        enabled: true
        users:
          - name: superuser
            password: superpassword
            mechanism: SCRAM-SHA-512
    external:
      enabled: false
    statefulset:
      replicas: 1
    console:
      enabled: false
    config:
      cluster:
        enable_shadow_linking: true